name: CublexAPI
version: ${version}
main: io.github.devbd1.cublexcore.Main
api-version: '1.21'
load: STARTUP
authors: [ DevBD1 ]
description: Spigot development library, mainly built for Cublex.net but its API can be used in other plugins.
website: https://dev.cublex.net
depend:
  - ProtocolLib
softdepend:
  - RealisticSeasons
  - PlaceholderAPI
commands:
  cublex:
    description: CublexCore main command
    usage: /cublex <help|reload|ver|getkey>
    permission: cublex.admin
permissions:
  cublexcore.admin:
    description: Allows admin access to any Cublex command
    default: op
  cublexcore.cmd.version:
    description: Allows access to /cublex version command