name: Corlex
version: '1.0-SNAPSHOT'
main: com.DevBD1.corlex.Main
api-version: '1.21'
load: STARTUP
authors: [ DevBD1 ]
description: Spigot development library, built for the latest version.
website: https://cublex.net
commands:
  testlang:
    description: Test localization messages
  corlex:
    description: Corlex admin command
    usage: /corlex reload
    permission: corlex.admin
permissions:
  corlex.admin:
    description: Allows Corlex admin commands
    default: op
