name: Corlex
version: ${version}
main: com.DevBD1.corlex.Main
api-version: '1.21'
load: STARTUP
authors: [ DevBD1 ]
description: Spigot development library, built for the latest version.
website: https://dev.cublex.net
depend:
  - ProtocolLib
softdepend:
  - RealisticSeasons
  - PlaceholderAPI
commands:
  corlex:
    description: Corlex command
    usage: /corlex <help|reload|test>
    permission: corlex.admin
permissions:
  corlex.admin:
    description: Allows admin access to Corlex commands
    default: op
