name: Corlex
version: '1.2.6'
main: com.DevBD1.corlex.Main
api-version: '1.21'
load: STARTUP
authors: [ DevBD1 ]
description: Spigot development library, built for the latest version.
website: https://cublex.net
softdepend:
  - RealisticSeasons
commands:
  corlex:
    description: Corlex command
    usage: /corlex <reload|test>
    permission: corlex.admin
permissions:
  corlex.admin:
    description: Allows admin access to Corlex commands
    default: op
